alias vim "/Applications/MacVim.app/Contents/MacOS/Vim"

alias gred "cd ~/Git/red/red/front_main2/"
alias gasura "cd ~/Git/red/asura/"

# Git
alias g "git"

alias ga "git add"
alias gaa "git add --all"
alias gapa "git add --patch"

alias gb "git branch"
alias gba "git branch -a"
alias gbl "git blame -b -w"
alias gbnm "git branch --no-merged"
alias gbr "git branch --remote"
alias gbs "git bisect"
alias gbsb "git bisect bad"
alias gbsg "git bisect good"
alias gbsr "git bisect reset"
alias gbss "git bisect start"

alias gc "git commit -v"
alias gc! "git commit -v --amend"
alias gcn! "git commit -v --no-edit --amend"
alias gca "git commit -v -a"
alias gca! "git commit -v -a --amend"
alias gcan! "git commit -v -a --no-edit --amend"
alias gcans! "git commit -v -a -s --no-edit --amend"
alias gcam "git commit -a -m"
alias gcb "git checkout -b"
alias gcf "git config --list"
alias gcl "git clone --recursive"
alias gclean "git clean -fd"
alias gcm "git checkout master"
alias gcd "git checkout develop"
alias gcmsg "git commit -m"
alias gco "git checkout"
alias gcount "git shortlog -sn"
alias gcp "git cherry-pick"
alias gcpa "git cherry-pick --abort"
alias gcpc "git cherry-pick --continue"
alias gcs "git commit -S"
alias gst "git status"
alias gss "git status -s"
alias ggpush "git push origin head"
alias gbf "git ci -am 'bugfix'"
alias gbda "git branch --no-color --merged | grep -vE 'develop|master' | command xargs -n 1 git branch -d "
